Repository Nexmo/api-specification, pull requests merged in 2020-07, with the labels that each got.

#333 Update description for csv_report_response
  definitions/reports.yml
Labels: review-app

#331 Remove unused numbers key + fix event_url example
  definitions/conversation.yml
Labels: review-app

#330 Examples for Account API
  definitions/account.yml
Labels: review-app

#334 Refactor Voice to use oneOf for use cases
  definitions/conversation.yml
  definitions/voice.v2.yml
  definitions/voice.yml
Labels: review-app

#337 Series of fixes captured in DEVX-3052
  definitions/reports.yml
Labels: review-app

#339 Fix incorrect version due to merge clash
  definitions/reports.yml
Labels: review-app

#340 Update to OAS renderer 2.0
  Gemfile
  Gemfile.lock
Labels: review-app, skip-version-check

#341 Add Subaccount error messages
  definitions/subaccounts.yml
Labels: review-app

#344 Add Beta label to Audit API
  definitions/audit.yml
Labels: review-app

#343 ASR Reports API
  definitions/reports.yml
Labels: review-app

#345 Correct length_timer description
  definitions/voice.yml
Labels: review-app

#346 Change company name from Nexmo to Vonage
  definitions/reports.yml
Labels: review-app

#347 Correct Transfer Request Example
  definitions/voice.yml
Labels: review-app

#348 Add Thai and Yue Chinese to the verify lg param
  definitions/verify.yml
Labels: review-app

#338 Removed wording that "Remaining Balance" was not being returned
  definitions/number-insight.yml
Labels: review-app

#328 Tweaked examples and some content types to make it clearer for tooling
  definitions/number-pools.yml
Labels: Do not merge, enhancement
