Repository Nexmo/api-specification, pull requests merged in 2020-06, with the labels that each got.

#320 Bump renderer
  Gemfile
  Gemfile.lock
Labels: review-app

#317 Clarify event_url requirements in VAPI create a call action
  definitions/voice.yml
Labels: review-app

#292 Add detail of responses for the error status codes to Numbers API
  definitions/numbers.yml
Labels: review-app

#321 Add Version change detection workflow
  .github/workflows/pull_request.yml
Labels: Do not merge, review-app, skip-version-check

#319 Break Voice API objects out to components section
  definitions/voice.v2.yml
  definitions/voice.yml
Labels: review-app

#324 OpenAPI Release workflow now supports multiple specs being edited in …
  .github/workflows/pull_request.yml
Labels: review-app, skip-version-check

#325 Mark as deprecated
  definitions/developer/messages.yml
Labels: review-app

#327 Verify API only returns 101 from the search endpoint
  definitions/verify.yml
Labels: review-app

#323 Add additional Spectral rules
  .spectral.yml
  .travis.yml
  definitions/account.yml
  definitions/application.v2.yml
  definitions/application.yml
  definitions/conversation.yml
  definitions/dispatch.yml
  definitions/messages-olympus.yml
  definitions/redact.yml
  definitions/reports.yml
  definitions/subaccounts.yml
  definitions/voice.yml
  definitions/vonage-business-cloud/vgis.yml
  functions/README.md
  functions/objectRequiredProperties.js
  functions/operationOrdering.js
  functions/requiredPropertyExample.js
Labels: review-app, skip-version-check

#329 Add Prettier
  .github/workflows/pull_request.yml
  README.md
  definitions/account.yml
  definitions/application.v2.yml
  definitions/application.yml
  definitions/audit.yml
  definitions/common/common_errors.yml
  definitions/conversation.v2.yml
  definitions/conversation.yml
  definitions/conversion.yml
  definitions/developer/messages.yml
  definitions/dispatch.yml
  definitions/external-accounts.yml
  definitions/media.yml
  definitions/messages-olympus.yml
  definitions/numbers.yml
  definitions/reports.yml
  definitions/sms.yml
  definitions/subaccounts.yml
  definitions/verify.yml
  definitions/voice.v2.yml
  definitions/voice.yml
  definitions/vonage-business-cloud/account.yml
  definitions/vonage-business-cloud/call-recording.yml
Labels: review-app, skip-version-check

#332 Add x-hide-request flag to Messages OAS
  definitions/dispatch.yml
  definitions/messages-olympus.yml
Labels: review-app, skip-version-check

#326 Update description of From and To in getCall(s) for Voice API
  definitions/voice.yml
Labels: review-app
