Repository Nexmo/api-specification, pull requests merged in 2020-04, with the labels that each got.

#274 Add reports sync endpoint
  definitions/reports.yml
Labels: Do not merge, review-app

#283 Add recent API changes to the Numbers spec
  definitions/numbers.yml
Labels: review-app

#287 Rename `messages_id` parameter to `id` in Reports
  definitions/reports.yml
Labels: review-app

#288 add client_ref to vapi v2
  definitions/voice.v2.yml
Labels: review-app

#269 Move Verify API over to use POST methods
  definitions/verify.yml
Labels: ready for review, review-app

#290 To number is a string
  definitions/developer/messages.yml
Labels: Do not merge, review-app

#286 Add client-ref field, error info and better examples for SMS API
  definitions/sms.yml
Labels: review-app
