Repository Nexmo/api-specification, pull requests merged in 2020-10, with the labels that each got.

#366 Fixes for get records
  definitions/reports.yml
Labels: review-app

#368 Update Ruby version
  .ruby-version
Labels: review-app, skip-version-check

#356 Add WebSocket Call product
  definitions/reports.yml
Labels: Do not merge, review-app

#363 Refreshing Applications API (and common errors)
  definitions/application.v2.yml
  definitions/common/common_errors.yml
Labels: review-app

#374 Conversation API beta/beta2 endpoints transition to v0.1/v0.2
  definitions/conversation.v2.yml
  definitions/conversation.yml
Labels: review-app

#376 Use nexmo's github action for creating review apps.
  .github/workflows/pull_request.yml
Labels: review-app, skip-version-check
