Repository Nexmo/api-specification, pull requests merged in 2021-12, with the labels that each got.

#468 spectral to v.5.9.2
  .github/workflows/ci.yml
Labels: review-app, skip-version-check

#355 Number pools
  definitions/common/common_errors.yml
  definitions/number-pools.yml
Labels: Do not merge, review-app

#454 Feature/number insight sync realtime
  definitions/number-insight.yml
Labels: review-app

#431 Meetings API - Phase 1
  definitions/meetings.yml
Labels: review-app
