Repository Nexmo/api-specification, pull requests merged in 2021-01, with the labels that each got.

#408 specify request id required condition
  definitions/verify.yml
Labels: review-app

#308 adding whatsapp provisioning API spec
  definitions/whatsapp-provisioning.yml
Labels: Do not merge, review-app

#411 Replace travis with GH actions.
  .github/workflows/ci.yml
  .travis.yml
Labels: review-app, skip-version-check

#410 Fixed a typo in the intial carrier NI info
  definitions/number-insight.yml
Labels: review-app

#399 Add subaccounts transfer-number API spec
  definitions/subaccounts.yml
Labels: Do not merge, review-app
