Repository Nexmo/api-specification, pull requests merged in 2021-05, with the labels that each got.

#436 Bump oas-renderer.
  Gemfile.lock
Labels: review-app, skip-version-check

#430 Add Languages
  json-schemas/ncco-schema.json
Labels: skip-version-check

#432 [SubAccount API] Add maxLength to Account name
  definitions/subaccounts.yml
Labels: review-app

#435 Fixed nullable for original carrier, removed roaming from standard
  definitions/number-insight.yml
Labels: review-app
