Repository Nexmo/api-specification, pull requests merged in 2021-11, with the labels that each got.

#453 DEVX-5755 Add Messages API v1 specifications
  definitions/messages-olympus.v01.yml
  definitions/messages-olympus.v1.yml
Labels: review-app

#455 reverted messages v1
  definitions/messages-olympus.v1.yml
  definitions/messages-olympus.yml
Labels: skip-version-check

#450 added version to messages capability
  definitions/application.v2.yml
Labels: review-app

#407 Messages v1
  Gemfile.lock
  definitions/messages.v0.yml
  definitions/messages.v1.yml
Labels: review-app

#456 renamed messages.v1 to messages to prevent api-errors path mismatch
  definitions/messages.yml
Labels: review-app

#457 Messages v1 - conflict fix
  definitions/messages-olympus.v0.yml
  definitions/messages-olympus.yml
Labels: review-app

#458 Messages v1 errors path fix
  definitions/messages-olympus.yml
Labels: review-app

#459 removed redundant file
  definitions/messages.yml
Labels: review-app, skip-version-check

#372 10DLC Public API
  definitions/10dlc.yml
  definitions/common/common_errors.yml
  definitions/common/hal_structures.yml
  definitions/messaging-engagements.yml
Labels: Do not merge, review-app

#420 Update sms.yml
  definitions/sms.yml
Labels: review-app
